project_name: zbc-go
release:
    github:
        owner: zeebe-io
        name: zbc-go
    draft: false
builds:
    -
        env:
            - CGO_ENABLED=0
        goos:
            - linux
            - darwin
            - windows
        goarch:
            - amd64
            - 386
        ignore:
            - goos: darwin
              goarch: 386
        main: ./cmd/main.go
        ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
        binary: zbctl
archive:
    format: tar.gz
    name_template: 'zbctl-{{ .Version }}-{{ .Os }}_{{ .Arch }}'
    replacements:
        darwin: Darwin
        linux: Linux
        windows: Windows
        amd64: x86_64
    format_overrides:
        - goos: windows
          format: zip
snapshot:
    name_template: SNAPSHOT-{{ .Commit }}
checksum:
    name_template: 'zbctl-{{ .Version }}_checksums.txt'
