language: go
sudo: required

services:
  - docker

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - "1.10"
  - tip

before_script:
  - docker run -p 51015:51015 -d camunda/zeebe:SNAPSHOT

script:
  - make test-protocol
  - make test-hexdump
  - make test-integration
  - make cov
  - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
