language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

script:
  - make test-protocol
  - make test-hexdump
  - make cov
  - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash || exit 1
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION =~ ^1\.9\.?[0-9]*$
